version: '3'

services:
  api:
    container_name: pet_manager
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true
    volumes:
      - ./:/go/api
    ports:
      - '3000:3000'
  db:
    image: mysql:8.0
    container_name: pet_manager_db
    env_file:
      - ../env/.env
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    environment:
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD
      TZ: Asia/Tokyo
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - '3306:3306'
    volumes:
      - dbdata:/var/lib/mysql
      - ./etc/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/init/:/docker-entrypoint-initdb.d
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD

volumes:
  dbdata:
    driver: local
